// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package tutorial

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUsers = `-- name: CreateUsers :one
INSERT INTO users (
  name, dob
) VALUES (
  $1, $2
)
RETURNING id, name, dob
`

type CreateUsersParams struct {
	Name string
	Dob  pgtype.Date
}

func (q *Queries) CreateUsers(ctx context.Context, arg CreateUsersParams) (User, error) {
	row := q.db.QueryRow(ctx, createUsers, arg.Name, arg.Dob)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.Dob)
	return i, err
}

const deleteUsers = `-- name: DeleteUsers :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUsers(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUsers, id)
	return err
}

const getUsers = `-- name: GetUsers :one
SELECT id, name, dob FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUsers(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUsers, id)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.Dob)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, dob FROM users
ORDER BY name
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.Name, &i.Dob); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUsers = `-- name: UpdateUsers :one
UPDATE users
  set name = $2,
  dob = $3
WHERE id = $1
RETURNING id, name, dob
`

type UpdateUsersParams struct {
	ID   int64
	Name string
	Dob  pgtype.Date
}

func (q *Queries) UpdateUsers(ctx context.Context, arg UpdateUsersParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUsers, arg.ID, arg.Name, arg.Dob)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.Dob)
	return i, err
}
